title: Testing
description: Remember the old saying. Cry once when you buy it or cry every time you use it.﻿
# url: 'https://mallinanga.github.io'
# baseurl: /nanga-forestry

permalink: pretty
timezone: Europe/Athens
verbose: false
sass:
  style: compressed

prose:
  media: 'media'
  ignore:
    - /_includes
    - /_layouts
    - _config.yml

gems:
  #- jekyll-menus
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'node_modules'
  - 's3_website.yml'
  - 'vendor'
